### ISSUE TITLE
Updating RaidExtractor for New Version

### ISSUE THREAD

**Issue by kenibrewer** [LukeCroteau/RaidExtractor#1]
I did some playing around with the code to try and get it to work with the new version of Raid. There is a hard coded line in MainForm.cs that reads:

` if (!process.MainModule.FileName.Contains("\\226\\"))`

Despite being in Raid "Version 3.0" the actual version number for the new process is actually 227. However, simply changing that hard-coded version check doesn't solve all the problems. RaidExtractor will start, but it will only export an empty Json file. I think the problem is that RaidExtractor is also hard-coded to scan specific memory addresses in the Raid program. The memory offset probably changes with each version. 

I've tried a little bit of memory scanning with CheatEngine, but I haven't been able to figure out what the new memory offsets are that will allow successful scanning of hero and artifact collection.

**Comment by LukeCroteau** [comment]
I pushed code in to update the Memory Location, but also allow Memloc hunting while debugging in VSCode.

While debugging, hold Control and click on the Save JSON button and it will give a set of likely memory locations.

See commits:
- 76ccb9cd325de4153c0b983812959d672c539a9d for Memloc Hunting
- 4e096ddd167f4b3e2448487fea3c72b2bb0fdbe1 for updated Memory location
