### ISSUE TITLE
Some Champions are missing

### ISSUE THREAD

**Issue by Draxxalon** [LukeCroteau/RaidExtractor#11]
There are a number of champs which the extractor does not understand.   Probably the newer ones :)

Here are the character ID's that were not extracted in my account:

CharacterID
--
5415
5380
5495
5420
5435
5380
5490

**Comment by morrelinko** [comment]
Made a pull request to resolve this here #10

**Comment by LukeCroteau** [comment]
Release 0.8.13 (34da5353e74d84a4bf58d2f23c125d4e010c69c2) Contains the fixes from #10

**Comment by morrelinko** [comment]
@LukeCroteau Just confirmed. The 0.8.13 build uses the old `hero_types.json` not the one from the patch

**Comment by LukeCroteau** [comment]
> @LukeCroteau Just confirmed. The 0.8.13 build uses the old `hero_types.json` not the one from the patch

That's strange, I grabbed the one straight out of the Repo.
I've re-uploaded the binary on the 0.8.13 build, and confirmed with the original submitter that this has the missing 5380 - Tigersoul champion.
