### ISSUE TITLE
0.8.14 - Champ Defence values are all 0

### ISSUE THREAD

**Issue by Draxxalon** [LukeCroteau/RaidExtractor#16]
In 0.8.14 all champs have a defence of 0

Sample:
      "fraction": "SacredOrder",
      "rarity": "Epic",
      "role": "Defense",
      "element": "Void",
      "awakenLevel": 0,
      "name": "Lightsworn",
      "health": 10575.0,
      "accuracy": 0.0,
      "attack": 494.0,
      **"defense": 0.0,**
      "criticalChance": 15.0,
      "criticalDamage": 50.0,
      "criticalHeal": 50.0,
      "resistance": 30.0,
      "speed": 97.0,
      "masteries": []

Base values exist in hero_types, so would appear to be somewhere in the code.

**Comment by Scippi** [comment]
It seems that the JSON-Field "defense" doesn't match the C# field "defence" in HeroType.cs.

**Comment by LukeCroteau** [comment]
This will be fixed in the next release.
Thanks @morrelinko
