### ISSUE TITLE
is faction supposed to be spelled fraction in the code?

### ISSUE THREAD

**Issue by F0RM4TION** [LukeCroteau/RaidExtractor#19]
in the heros code, faction is spelled fraction, is that a converting bug or is it like that from the game code? thanks :)

**Comment by LukeCroteau** [comment]
Funny enough, that's how the RSL team have things inside of their binary, they name it Fraction.
Probably a typo that got stuck.
In the interest of keeping the data homogeneous across all the projects currently tangled together, I'm not going to change it for now.
Maybe in the future.
