### ISSUE TITLE
v 0.8.11 not extracting artifacts

### ISSUE THREAD

**Issue by novice-101** [LukeCroteau/RaidExtractor#2]
Hi Luke

The new patched 0.8.11 version now starts up and creates the .json file but only in ~250KB size i.e. does not contain the artifacts (with my full storage of 700 plus ones equipped plus accessories the file should be around 2.2MB). 
Well kind of, it exported 24 while previously with an earlier Da-teach version after RAID got an update I got only one "null" artifact. But these 24 "artifacts" are not correct, I think most of the data is wrong when making a query in Excel. Id's don't match (many negative values etc).

**Comment by kenibrewer** [comment]
Yeah. I'm getting the same bogus data. I think we identified the wrong memory address to start scanning artifacts from. I'll scan and try to find the real one.

**Comment by LukeCroteau** [comment]
You're right. I'm digging into the memory addresses right now.

When I added the Scanning code, I failed to account for the alternate method that Da-Teach added in his last public revision of the code.

I've modified the code now, and am starting scanning. I'll update when I know more.

**Comment by morrelinko** [comment]
Made a pull request that should fix this.

**Comment by kenibrewer** [comment]
@morrelinko Can you share the process you used for figuring out these new offsets?
