### ISSUE TITLE
is the new gear supposed to be numbers?

### ISSUE THREAD

**Issue by F0RM4TION** [LukeCroteau/RaidExtractor#20]
just wonderig if the fatal, untouchable and frostbite gears "set kind" is supposed to be numbers rather than the set name. 
fatal is 41, untouchable is 40 and frostbite is 42

thanks

**Comment by LukeCroteau** [comment]
This will be fixed in the next release. Thanks!

**Comment by LukeCroteau** [comment]
Now available in release v0.8.16 (a343c4e)
