### ISSUE TITLE
New Web Hosting

### ISSUE THREAD

**Issue by kenibrewer** [LukeCroteau/RaidExtractor#3]
The URL that RaidExtractor used to upload data to is no longer accessible. We could just focus on restoring the Artifact/Hero extraction functionality, but I thought the artifact build optimization interface was decent (although interminably slow) and so it might be worth restoring the website too.

**Comment by LukeCroteau** [comment]
Just as an update..

I've restored this functionality with the v0.8.15 release found here:
https://github.com/LukeCroteau/RaidExtractor/releases/tag/v0.8.15

This is **purely a bring forward** of the Original Website and Optimization functionality. No changes have been made other than cosmetic changes to point to this repository.

I don't expect this functionality to exist for long, as there are already several people vying to create new ones.
