### ISSUE TITLE
Pull Champion Portrait Images into the website.

### ISSUE THREAD

**Issue by cmarabate** [LukeCroteau/RaidExtractor#34]
I would be willing to help with this if someone is able to teach me how. I am a web developer but I am not very familiar with angular and much more familiar with React and I have no idea how to pull data from the game.

I also would love to learn how I could add a file upload button to my Gatsby site that would allow users to upload the json file exported by this app and have it uploaded to localStorage for me to pull all the data from. If you happen to know how I could do that, I would greatly appreciate it and will try to help out in any way I can.

Thanks,

Chris

**Comment by Digimont** [comment]
While I understand the desire to extract these directly from the game, I solved this for my little project by scraping them from Ayumilove. I have all the thumbnails and could simply provide them if that is a suitable short or even permanent solution.

**Comment by cmarabate** [comment]
@Digimont
Yeah, that works. I have them all as well but many of mine I had to screengrab from their update highlights posts so they are not all exactly the same size which bugs me lol, so if all of yours are exactly the same dimensions I would greatly appreciate it if you provide them =).

Thanks!
