### ISSUE TITLE
Add latest used champions foreach game location

### ISSUE THREAD

**Issue by Tabaki001** [LukeCroteau/RaidExtractor#35]
It would be interesting adding to the data the compositions used for each dungeons / locations
For example :
- dragon : RG, Seer, MM, Renagate, Lydia
- atk arena (1v1) : ...
- ...

**Comment by LukeCroteau** [comment]
This would require quite a bit of data collection, I think.
I'm not sure if this can be extracted. I can take a look sometime.

**Comment by Tabaki001** [comment]
I made this page for import JSON data on my web site (french only for the moment)
https://myclanbossteam.fr/champions/ma-box/

I also make some pages for share data for clan's player. (demo also french : https://myclanbossteam.fr/boxes/partage-de-box-demo/)

To help people on the first import it could be usefull to also import 'user last used team composition' for 'all location'

**Comment by LukeCroteau** [comment]
This has been added in the 0.8.30.0 release of the extractor.

Please take a look at the release, and attached notes, and make sure this solves what you need!
