### ISSUE TITLE
All "top row" Masteries are out by 1

### ISSUE THREAD

**Issue by Digimont** [LukeCroteau/RaidExtractor#36]
![image](https://user-images.githubusercontent.com/76764994/109239872-46644980-7826-11eb-888f-7d7dcb1421d3.png)

As there are only 2 masteries in the top row 500113 shouldn't exist. I've checked my characters in game and all numbers in the 500x1x series are +1 from what they should be. All other mastery rows are fine.
I don't know if the game is giving you these numbers (in which case a Plarium bug, which you could perhaps correct in the extraction, or we can cater for in our own tools), or you are somehow adding one.

**Comment by LukeCroteau** [comment]
@Digimont
Looking at the Static data, around line 6466 you should see the skill descriptions for the Masteries. I've included a screenshot below.
It looks to me like 500113 is the Crit Rate +5% Mastery.

These identifiers are internal to them, so I'd imagine there's not a whole lot I can do about these numbers. It probably just seems mentally wrong to have it be "3", but it appears correct.

![image](https://user-images.githubusercontent.com/7110469/109664510-30fb6200-7b3b-11eb-90a6-581783b097c3.png)

**Comment by Digimont** [comment]
No problem Luke. I said it could be a Plarium bug!
