### ISSUE TITLE
v0.8.24 - Empty champions masteries 

### ISSUE THREAD

**Issue by Tabaki001** [LukeCroteau/RaidExtractor#39]
Hi,
I extracted the game data in JSON with version 0.8.24 and no champions have masteries.

IG: 
![image](https://user-images.githubusercontent.com/77483172/111591286-8a17f680-87c7-11eb-912b-6981c53b663d.png)

in JSON:
`{
      "id": 2527,
      "typeId": 1496,
      "grade": "Stars6",
      "level": 60,
      "experience": 0,
      "fullExperience": 3624238,
      "locked": true,
      "inStorage": false,
      "artifacts": [
        802,
        6839,
        7838
      ],
      "fraction": "HighElves",
      "rarity": "Rare",
      "role": "Attack",
      "element": "Magic",
      "awakenLevel": 6,
      "name": "Elhain",
      "health": 14370.0,
      "accuracy": 0.0,
      "attack": 1233.0,
      "defense": 837.0,
      "criticalChance": 15.0,
      "criticalDamage": 57.0,
      "criticalHeal": 50.0,
      "resistance": 30.0,
      "speed": 107.0,
      "masteries": []
    },`

JSON (0.8.23 ou 0.8.22):
`{
		"id":2527,
		"typeId":1496,
		"grade":"Stars6",
		"level":60,
		"experience":0,
		"fullExperience":3624238,
		"locked":true,
		"inStorage":false,
		"artifacts":[802,6839,7838],
		"fraction":"HighElves",
		"rarity":"Rare",
		"role":"Attack",
		"element":"Magic",
		"awakenLevel":6,
		"name":"Elhain",
		"health":14370,
		"accuracy":0,
		"attack":1233,
		"defense":837,
		"criticalChance":15,
		"criticalDamage":57,
		"criticalHeal":50,
		"resistance":30,
		"speed":107,
		"masteries":[500113,500122,500131,500132,500141,500151,500161,500212,500222,500221,500232,500242,500253,500254,500143]
		}`

**Comment by LukeCroteau** [comment]
@Tabaki001 Thank you!
Please check Release 0.8.24.1 for the fix. It looks like adding the Marker for I, II, III caused the hero structure to change, and mastery extraction wouldn't work.

Yet another reason for me to build some automated testing into this project to avoid these problems. I already look at a lot of stuff, but I didn't look at this one!

**Comment by Tabaki001** [comment]
Thanks to you @LukeCroteau.
