### ISSUE TITLE
3.30 champions : no data

### ISSUE THREAD

**Issue by Tabaki001** [LukeCroteau/RaidExtractor#40]
Sorry, new issue.

on Json I do not have full data for Cadriel (same for Astralon, Abyssal) : 

Json of Cadriel : 
`{
      "id": 19603,
      "typeId": 5766,
      "grade": "Stars6",
      "level": 60,
      "experience": 0,
      "fullExperience": 2974475,
      "locked": true,
      "inStorage": false,
      "artifacts": [],
      "awakenLevel": 0,
      "health": 0.0,
      "accuracy": 0.0,
      "attack": 0.0,
      "defense": 0.0,
      "criticalChance": 0.0,
      "criticalDamage": 0.0,
      "criticalHeal": 0.0,
      "resistance": 0.0,
      "speed": 0.0,
      "masteries": []
    },`
(No faction, name, affinity, rarety, role and element keys, no stats values)

**Comment by LukeCroteau** [comment]
Yep, this is a known issue.

None of the new champions from the last 2 groups of new champs have been brought in yet.

I need to write a new parser to take the Static Data and output the hero_types.json

My plan is to work on that first, so that as the static data gets updated, I can easily update the file. Our maintainer who was doing it has run into a bit of misfortune, and hasn't been able to update the file lately.

**Comment by Leomaradan** [comment]
A contributor on one of my repository has added a list on champions with internal ID (the id that correspond to your typeId). I don't know if it's usefull for you or not, but here is the file https://raw.githubusercontent.com/McRadane/raid-data/master/champions-by-id.json

I checked with my extracted data, and it seems to correspond to missing champions

**Comment by zerfl** [comment]
I have started some work on extracting the static data. You can find the progress in the static-hero-data branch in my fork or here: https://github.com/zerfl/RaidExtractor/commit/1e3f11dbf369c3f0629d445648751339419f711f - Caution: it's far from complete and the code / structure is quite messy. Simple static extraction to json, albeit in the same artifacts.json file for now, is working though.

I am reading the data from the SharedModel.Meta.Heroes.HeroType type, which is referenced by the ClientStaticDataManager, which in turn is referenced by the StaticDataManager on AppModel.

However, I am stuck at extracting data that is accessed by properties. Many of these properties are not auto-properties and hence have no backing field that you can easily read. While some of them follow an easy to implement logic (e.g. IsBoss is simply this.BossData != null) others like IsBaseType are implemented using a more complex getter. I am specficially talking about these:

![image](https://user-images.githubusercontent.com/219458/113598635-b8a62600-963d-11eb-8ce7-0666422e190f.png)

Any hints are appreciated.

**Comment by zerfl** [comment]
Until #53 is merged you can grab an up-to-date version of the file here: https://gist.githubusercontent.com/zerfl/7a5ba5de7ee3be7d10d0cbc03fb9b77a/raw/fef7bc0d8d18d11f91a3bfa0fc5d7217c5a1d383/hero_types.json

**Comment by LukeCroteau** [comment]
> I have started some work on extracting the static data. You can find the progress in the static-hero-data branch in my fork or here: [zerfl@1e3f11d](https://github.com/zerfl/RaidExtractor/commit/1e3f11dbf369c3f0629d445648751339419f711f) - Caution: it's far from complete and the code / structure is quite messy. Simple static extraction to json, albeit in the same artifacts.json file for now, is working though.

I'm just kinda looking through this right now, as a result of the merge request.

Looks like you're off to a promising start!

I'll merge this and dump out a release in the morning. Thanks so much for your efforts!

**Comment by LukeCroteau** [comment]
Release 0.8.27.1 has been created with the updated hero_types.json

**Comment by zerfl** [comment]
> Looks like you're off to a promising start!

I paused my work on it in the scope of the C# extractor for now as there's no way for me to call the actual getters in the proper address space without injecting a DLL.

So for now I have put my efforts into putting out a C++ DLL instead that you can inject into the process. It generates the hero_types.json that was merged with #53. The code is available at https://github.com/zerfl/StaticRaidExtraction.

What I am planning to do is write a BepInEx plugin at some point, that will extract the data and hopefully needs less maintenance compared to the C++ DLL.

Alternatively, we could easily call a method from within the process that generates a complete static data file like https://github.com/Da-Teach/RaidStaticData/blob/master/static_data.json. This would require rewriting many parts of the extractor tho. Just a thought.

**Comment by LukeCroteau** [comment]
> So for now I have put my efforts into putting out a C++ DLL instead that you can inject into the process. It generates the hero_types.json that was merged with #53. The code is available at https://github.com/zerfl/StaticRaidExtraction.
> 
> What I am planning to do is write a BepInEx plugin at some point, that will extract the data and hopefully needs less maintenance compared to the C++ DLL.
> 

Before you go too far down this road, I want to caution you.

Plarium has mentioned several times that if a tool is injecting itself directly, and calling methods straight out of the EXE, they **DO** have a problem with that. Memory peeking isn't a problem to them, but hooking directly into the exe is not something they're happy with.

I think I'd prefer if we attempt to not inject into their code from something inside this repository. I'd like for us to remain as above board as we can, to prevent Plarium's wrath. I'm willing to hear other people's opinions on the matter.

**Comment by zerfl** [comment]
I appreciate the heads up. Everyone should feel safe using this tool, and doing more than memory reading goes way beyond the scope of this project, I agree. That's why I focused on dealing with the extraction for this particular data outside of this repo.

**Comment by LukeCroteau** [comment]
I think @zerfl is pretty close to always having the hero_types.json updated pretty regularly.

I'm going to close this, and if we find it's still a problem in the future, we can bring it back up.
