### ISSUE TITLE
Extract each champs Power

### ISSUE THREAD

**Issue by cmarabate** [LukeCroteau/RaidExtractor#43]
Would it be possible to extract the Power of each champ into the json file?
![image](https://user-images.githubusercontent.com/12236062/112743140-bae3f280-8f62-11eb-8ba2-a5aef18d6a44.png)

I'm thinking that this would allow me to sort all the extracted champs in the same order they are displayed in-game.

I already have them sorted by Rarity then Grade then Level then Awaken Level. The next ingredient I must acquire is Power! 😈

Thanks, I can't wait to share what I have been working on.

**Comment by cmarabate** [comment]
Perfect, thanks! Let me know what you find out, I really hope it is extractable 😁.

**Comment by zerfl** [comment]
I don't think we can make it happen without injecting code into the application, which is beyond the scope of this project. Hero power is calculated on-demand when selecting a champion, calculating team battle power, and so on. It's not available at all times which is probably why there isn't any option to sort champions by power in-game.

You can test this by putting a breakpoint on CalcHeroPower() and selecting a hero in the champions view. It's defined as an extension method for the Hero object and its signature is `CalcHeroPower(this Hero hero, long userId, UserAccount account, UserArtifactData artifactData, UserVillageData villageData, UserArenaData arenaData)`. 

I would really love to be proven wrong, though!

**Comment by cmarabate** [comment]
That is a shame... Maybe if we can find out the exact calculation they use to calculate hero power, we could do the calculation ourselves as long as all the data that is needed to perform the calculation is able to be extracted.

**Comment by kfishkin** [comment]
I did some Googling on this a while ago, it seems Plarium has revealed nothing about the exact calculation, and attempts to reverse-engineer it have failed :(

**Comment by cmarabate** [comment]
Damn, oh well.
