### ISSUE TITLE
No web output option?

### ISSUE THREAD

**Issue by WickedShadows** [LukeCroteau/RaidExtractor#51]
Newest version does not give me the view on website (or whatever it used to be) anymore.
![Raid Extractor](https://user-images.githubusercontent.com/22035816/113488108-3ff66c80-9479-11eb-886d-84a5d02c3caa.jpg)

**Comment by LukeCroteau** [comment]
You are correct.

Unfortunately, nobody seemed interested in maintaining the Web code anymore. 

I warned everyone for 2 months before giving up on the illusion that we were going to do keep it available. :(

If you take a look at the front page of the repository, there are links to a few tools where you can upload the JSON to, to have similar tools available. Potentially at some point in the future, I will re-add the Website view button, and have it select one of these tools. That would be up to the tool maintainers if they'd like that functionality.

**Comment by cmarabate** [comment]
> Potentially at some point in the future, I will re-add the Website view button, and have it select one of these tools. That would be up to the tool maintainers if they'd like that functionality.

@LukeCroteau I would love an app that would automatically add the JSON data to the localStorage of my website!!! Is that something you can do with any website even a React site? I don't know anything about app development sadly but that is something I would love to learn how to do.

**Comment by zerfl** [comment]
The data can be sent to virtually any target site. It's up to the website to handle receiving and processing the data (i.e. parsing/storing it in localStorage and acting upon it).
