### ISSUE TITLE
Enhancement: Extract Books Data for Champions

### ISSUE THREAD

**Issue by Digimont** [LukeCroteau/RaidExtractor#52]
(getting in the queue, No rush, as I have a workaround method)...

Currently, I'm using the static data's Booked and Unbooked cooldowns for my CB and Arena calculators, the user has to manually amend those fields to get accurate calculations. Would love to get the actual books (however the data can be extracted) on each move (A1-A6 as they show in the data), as this would eliminate another point where user errors can occur. 

I'm sure others would find this useful too.

**Comment by LukeCroteau** [comment]
Yeah, this is a good call. It's on the list!

**Comment by LukeCroteau** [comment]
This has been added in and released into the wild!
