### ISSUE TITLE
Add version of tool to extracted .json

### ISSUE THREAD

**Issue by Digimont** [LukeCroteau/RaidExtractor#56]
Currently, if a .json has been generated by an out-of-date version of Raid Extractor, there's no way someone developing tools can identify that - it either works or doesn't. Could you please output the version as the first item of the .json? We'll all have to change our code, but we can then identify and reject old data files.

**Comment by LukeCroteau** [comment]
I've debated this at length with myself.

I'm not going to add this field at the beginning of the file.

However, if you're processing JSON in a standard way, e.g. identifying that the Top Level (currently) has 6 Lists (artifacts, heroes, arenaLeague, greatHall, shards, stagePresets), and parsing JSON in the standard way (only looking at the individual items you care about)...

I'm going to add a 7th item to the Top Level, called *fileVersion*.

This will be a simple string with the Major+Minor version of the extractor that generated this file.

My hope is that, between Builds (simple Address updates, etc) we wouldn't change the JSON structure.
Should we add something, or change the structure of the items in some way, we should be updating the Minor version number.

I believe at this time, Extractor should probably at least be a 1.0 release, given that it's proven, it works, and other things rely on it for their operation.

I'll be committing a fix to close this issue momentarily, under these guidelines.
