### ISSUE TITLE
Build automated method for detecting new memory offsets when Raid is patched

### ISSUE THREAD

**Issue by kenibrewer** [LukeCroteau/RaidExtractor#7]
While we certainly can't automatically patch memory offset problems automatically when Raid changes key data structures, but it would be great if we had a fallback option for detecting the correct memory offsets that works when Raid is patched.

**Comment by LukeCroteau** [comment]
We've found a great way to get all offsets, including a lot of data we previously didn't have access to.

I'm working on a pipeline right now to extract the offset data more programmatically.

**Comment by pprocacci** [comment]
I'm quite interested in the pipeline you are referring to.
Just recently I decided to write my own optimizer in C.
This was before I discovered your source code.
I'd be super appreciative if you could share this information as that's something I'd like to incorporate into my personal project.

**Comment by LukeCroteau** [comment]
@pprocacci 
I've got a VM with nothing installed by Plarium Play and Raid.
I've built myself a nice set of Python scripts to extract the memory addresses I'm currently using (plus some I'll be using in the future) and dump myself a nicely formatted C# class with all the addresses that I'll need.

It worked pretty splendidly today.

I'll think about writing up a tutorial, and committing those scripts to this repository, in the next little bit.

**Comment by Doorjam** [comment]
looks like the pay version is out now.. hope original guy atleast got a decent deal with HH. Any starter tips on python scripts I should look into? Been a long time since I poked around code lol..

**Comment by pprocacci** [comment]
Doubtful that Plarium would do anything.  RaidExtractor doesn't alter memory or game state or anything like that.
It just reads from memory.  Ideally I'd like to see them provide a simple API to gather that data, but that's wishful thinking.

I personally come from a super strong FreeBSD background, so windows isn't really my thing.
With that said, I was able to find everything I needed from the extracted exe mainly using Il2CppDumper / dnSpy / Cheat Engine.

There's a couple of things I don't know and the one big thing is how to automatically find the needed memory offsets from the beginning of GameAssembly.dll.  It's obviously stored somewhere and it's my hopes that Luke truly has found "the way" of doing it.  I'm currently and unshamefully(sp) waiting to "steal" some of the logic.  Every new build will yield new ones, and that's teh suck.

My strength isn't C#; again I'm from a unix background so my strength is asm/C, but if more hands are needed I could certainly entertain the thought of helping where applicable.  Just need to get familiar with the language (and Windows for that matter).

As for where to start and what's needed, it beats me as I was just looking for a way to find the initial memory offsets from GameAssembly.dll, ran into this repo, and was bummed that the offsets were static.  ;)  I'll leave this bit up to the maintainers.

**Comment by LukeCroteau** [comment]
> With that said, I was able to find everything I needed from the extracted exe mainly using Il2CppDumper / dnSpy / Cheat Engine.

What @pprocacci did is basically what I have done, I've just added a layer of semi-automation on top of it to extract all the things I need.

**Comment by LukeCroteau** [comment]
Commit 9836b539a876cb2234c25d132a7bb3655181153f goes a long way towards doing this, but it's hacky. It's a part of my early pipeline, which was pretty important to getting Today's update handled. (Looks like they have added some extra information, so alignment was way off today after the update.)

**Comment by LukeCroteau** [comment]
@SteveJRose added in an excellent PR that has taken care of this.
